// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocess_mini_request_object.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Coprocess {

  /// <summary>Holder for reflection information generated from coprocess_mini_request_object.proto</summary>
  public static partial class CoprocessMiniRequestObjectReflection {

    #region Descriptor
    /// <summary>File descriptor for coprocess_mini_request_object.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CoprocessMiniRequestObjectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNjb3Byb2Nlc3NfbWluaV9yZXF1ZXN0X29iamVjdC5wcm90bxIJY29wcm9j",
            "ZXNzGiBjb3Byb2Nlc3NfcmV0dXJuX292ZXJyaWRlcy5wcm90byLTBQoRTWlu",
            "aVJlcXVlc3RPYmplY3QSOgoHaGVhZGVycxgBIAMoCzIpLmNvcHJvY2Vzcy5N",
            "aW5pUmVxdWVzdE9iamVjdC5IZWFkZXJzRW50cnkSQQoLc2V0X2hlYWRlcnMY",
            "AiADKAsyLC5jb3Byb2Nlc3MuTWluaVJlcXVlc3RPYmplY3QuU2V0SGVhZGVy",
            "c0VudHJ5EhYKDmRlbGV0ZV9oZWFkZXJzGAMgAygJEgwKBGJvZHkYBCABKAkS",
            "CwoDdXJsGAUgASgJEjgKBnBhcmFtcxgGIAMoCzIoLmNvcHJvY2Vzcy5NaW5p",
            "UmVxdWVzdE9iamVjdC5QYXJhbXNFbnRyeRI/CgphZGRfcGFyYW1zGAcgAygL",
            "MisuY29wcm9jZXNzLk1pbmlSZXF1ZXN0T2JqZWN0LkFkZFBhcmFtc0VudHJ5",
            "EkkKD2V4dGVuZGVkX3BhcmFtcxgIIAMoCzIwLmNvcHJvY2Vzcy5NaW5pUmVx",
            "dWVzdE9iamVjdC5FeHRlbmRlZFBhcmFtc0VudHJ5EhUKDWRlbGV0ZV9wYXJh",
            "bXMYCSADKAkSNAoQcmV0dXJuX292ZXJyaWRlcxgKIAEoCzIaLmNvcHJvY2Vz",
            "cy5SZXR1cm5PdmVycmlkZXMaLgoMSGVhZGVyc0VudHJ5EgsKA2tleRgBIAEo",
            "CRINCgV2YWx1ZRgCIAEoCToCOAEaMQoPU2V0SGVhZGVyc0VudHJ5EgsKA2tl",
            "eRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaLQoLUGFyYW1zRW50cnkSCwoD",
            "a2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARowCg5BZGRQYXJhbXNFbnRy",
            "eRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBGjUKE0V4dGVuZGVk",
            "UGFyYW1zRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Coprocess.CoprocessReturnOverridesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Coprocess.MiniRequestObject), global::Coprocess.MiniRequestObject.Parser, new[]{ "Headers", "SetHeaders", "DeleteHeaders", "Body", "Url", "Params", "AddParams", "ExtendedParams", "DeleteParams", "ReturnOverrides" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MiniRequestObject : pb::IMessage<MiniRequestObject> {
    private static readonly pb::MessageParser<MiniRequestObject> _parser = new pb::MessageParser<MiniRequestObject>(() => new MiniRequestObject());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MiniRequestObject> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Coprocess.CoprocessMiniRequestObjectReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MiniRequestObject() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MiniRequestObject(MiniRequestObject other) : this() {
      headers_ = other.headers_.Clone();
      setHeaders_ = other.setHeaders_.Clone();
      deleteHeaders_ = other.deleteHeaders_.Clone();
      body_ = other.body_;
      url_ = other.url_;
      params_ = other.params_.Clone();
      addParams_ = other.addParams_.Clone();
      extendedParams_ = other.extendedParams_.Clone();
      deleteParams_ = other.deleteParams_.Clone();
      ReturnOverrides = other.returnOverrides_ != null ? other.ReturnOverrides.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MiniRequestObject Clone() {
      return new MiniRequestObject(this);
    }

    /// <summary>Field number for the "headers" field.</summary>
    public const int HeadersFieldNumber = 1;
    private static readonly pbc::MapField<string, string>.Codec _map_headers_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 10);
    private readonly pbc::MapField<string, string> headers_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Headers {
      get { return headers_; }
    }

    /// <summary>Field number for the "set_headers" field.</summary>
    public const int SetHeadersFieldNumber = 2;
    private static readonly pbc::MapField<string, string>.Codec _map_setHeaders_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 18);
    private readonly pbc::MapField<string, string> setHeaders_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> SetHeaders {
      get { return setHeaders_; }
    }

    /// <summary>Field number for the "delete_headers" field.</summary>
    public const int DeleteHeadersFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_deleteHeaders_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> deleteHeaders_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DeleteHeaders {
      get { return deleteHeaders_; }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 4;
    private string body_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Body {
      get { return body_; }
      set {
        body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 5;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 6;
    private static readonly pbc::MapField<string, string>.Codec _map_params_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 50);
    private readonly pbc::MapField<string, string> params_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Params {
      get { return params_; }
    }

    /// <summary>Field number for the "add_params" field.</summary>
    public const int AddParamsFieldNumber = 7;
    private static readonly pbc::MapField<string, string>.Codec _map_addParams_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 58);
    private readonly pbc::MapField<string, string> addParams_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> AddParams {
      get { return addParams_; }
    }

    /// <summary>Field number for the "extended_params" field.</summary>
    public const int ExtendedParamsFieldNumber = 8;
    private static readonly pbc::MapField<string, string>.Codec _map_extendedParams_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 66);
    private readonly pbc::MapField<string, string> extendedParams_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> ExtendedParams {
      get { return extendedParams_; }
    }

    /// <summary>Field number for the "delete_params" field.</summary>
    public const int DeleteParamsFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_deleteParams_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> deleteParams_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> DeleteParams {
      get { return deleteParams_; }
    }

    /// <summary>Field number for the "return_overrides" field.</summary>
    public const int ReturnOverridesFieldNumber = 10;
    private global::Coprocess.ReturnOverrides returnOverrides_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Coprocess.ReturnOverrides ReturnOverrides {
      get { return returnOverrides_; }
      set {
        returnOverrides_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MiniRequestObject);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MiniRequestObject other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Headers.Equals(other.Headers)) return false;
      if (!SetHeaders.Equals(other.SetHeaders)) return false;
      if(!deleteHeaders_.Equals(other.deleteHeaders_)) return false;
      if (Body != other.Body) return false;
      if (Url != other.Url) return false;
      if (!Params.Equals(other.Params)) return false;
      if (!AddParams.Equals(other.AddParams)) return false;
      if (!ExtendedParams.Equals(other.ExtendedParams)) return false;
      if(!deleteParams_.Equals(other.deleteParams_)) return false;
      if (!object.Equals(ReturnOverrides, other.ReturnOverrides)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Headers.GetHashCode();
      hash ^= SetHeaders.GetHashCode();
      hash ^= deleteHeaders_.GetHashCode();
      if (Body.Length != 0) hash ^= Body.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      hash ^= Params.GetHashCode();
      hash ^= AddParams.GetHashCode();
      hash ^= ExtendedParams.GetHashCode();
      hash ^= deleteParams_.GetHashCode();
      if (returnOverrides_ != null) hash ^= ReturnOverrides.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      headers_.WriteTo(output, _map_headers_codec);
      setHeaders_.WriteTo(output, _map_setHeaders_codec);
      deleteHeaders_.WriteTo(output, _repeated_deleteHeaders_codec);
      if (Body.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Body);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Url);
      }
      params_.WriteTo(output, _map_params_codec);
      addParams_.WriteTo(output, _map_addParams_codec);
      extendedParams_.WriteTo(output, _map_extendedParams_codec);
      deleteParams_.WriteTo(output, _repeated_deleteParams_codec);
      if (returnOverrides_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(ReturnOverrides);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += headers_.CalculateSize(_map_headers_codec);
      size += setHeaders_.CalculateSize(_map_setHeaders_codec);
      size += deleteHeaders_.CalculateSize(_repeated_deleteHeaders_codec);
      if (Body.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Body);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      size += params_.CalculateSize(_map_params_codec);
      size += addParams_.CalculateSize(_map_addParams_codec);
      size += extendedParams_.CalculateSize(_map_extendedParams_codec);
      size += deleteParams_.CalculateSize(_repeated_deleteParams_codec);
      if (returnOverrides_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReturnOverrides);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MiniRequestObject other) {
      if (other == null) {
        return;
      }
      headers_.Add(other.headers_);
      setHeaders_.Add(other.setHeaders_);
      deleteHeaders_.Add(other.deleteHeaders_);
      if (other.Body.Length != 0) {
        Body = other.Body;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      params_.Add(other.params_);
      addParams_.Add(other.addParams_);
      extendedParams_.Add(other.extendedParams_);
      deleteParams_.Add(other.deleteParams_);
      if (other.returnOverrides_ != null) {
        if (returnOverrides_ == null) {
          returnOverrides_ = new global::Coprocess.ReturnOverrides();
        }
        ReturnOverrides.MergeFrom(other.ReturnOverrides);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            headers_.AddEntriesFrom(input, _map_headers_codec);
            break;
          }
          case 18: {
            setHeaders_.AddEntriesFrom(input, _map_setHeaders_codec);
            break;
          }
          case 26: {
            deleteHeaders_.AddEntriesFrom(input, _repeated_deleteHeaders_codec);
            break;
          }
          case 34: {
            Body = input.ReadString();
            break;
          }
          case 42: {
            Url = input.ReadString();
            break;
          }
          case 50: {
            params_.AddEntriesFrom(input, _map_params_codec);
            break;
          }
          case 58: {
            addParams_.AddEntriesFrom(input, _map_addParams_codec);
            break;
          }
          case 66: {
            extendedParams_.AddEntriesFrom(input, _map_extendedParams_codec);
            break;
          }
          case 74: {
            deleteParams_.AddEntriesFrom(input, _repeated_deleteParams_codec);
            break;
          }
          case 82: {
            if (returnOverrides_ == null) {
              returnOverrides_ = new global::Coprocess.ReturnOverrides();
            }
            input.ReadMessage(returnOverrides_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
